variable "aws_region" {
  description = "AWS region for the free-tier friendly serverless stack."
  type        = string
  default     = "us-east-1"
}

variable "function_zip" {
  description = "Path to the Lambda deployment zip generated by make build-lambda."
  type        = string
  default     = "../function.zip"
}

variable "whatsapp_access_token" {
  description = "Meta WhatsApp Cloud API access token."
  type        = string
  sensitive   = true
}

variable "whatsapp_phone_number_id" {
  description = "Meta WhatsApp phone number ID."
  type        = string
  default     = ""
}

variable "whatsapp_verify_token" {
  description = "Random token used by Meta during webhook verification."
  type        = string
  sensitive   = true
}

variable "whatsapp_app_secret" {
  description = "Meta app secret used to verify X-Hub-Signature-256."
  type        = string
  sensitive   = true
}

variable "openai_api_key" {
  description = "OpenAI API key."
  type        = string
  sensitive   = true
}

variable "openai_model" {
  description = "OpenAI model used by the NLP service."
  type        = string
  default     = "gpt-5.4-nano"
}

variable "rdstation_token" {
  description = "RD Station CRM token."
  type        = string
  sensitive   = true
}

variable "log_level" {
  description = "Application log level."
  type        = string
  default     = "INFO"
}

variable "nlp_context_window" {
  description = "Number of previous messages sent to the NLP service."
  type        = number
  default     = 10
}
