variable "aws_region" {
  description = "AWS region for the free-tier friendly serverless stack."
  type        = string
  default     = "us-east-1"
}

variable "function_zip" {
  description = "Path to the Lambda deployment zip generated by make build-lambda."
  type        = string
  default     = "../function.zip"
}

variable "lambda_memory_size" {
  description = "Lambda memory in MB. 128 MB keeps the function in the cheapest/free-tier friendly compute band."
  type        = number
  default     = 128
}

variable "dynamodb_read_capacity" {
  description = "Provisioned DynamoDB read capacity units. Keep low to stay inside the free tier for light usage."
  type        = number
  default     = 1
}

variable "dynamodb_write_capacity" {
  description = "Provisioned DynamoDB write capacity units. Keep low to stay inside the free tier for light usage."
  type        = number
  default     = 1
}

variable "api_throttle_burst_limit" {
  description = "HTTP API burst throttle guardrail to reduce accidental request spikes."
  type        = number
  default     = 5
}

variable "api_throttle_rate_limit" {
  description = "HTTP API steady-state requests per second throttle guardrail."
  type        = number
  default     = 2
}

variable "whatsapp_access_token" {
  description = "Meta WhatsApp Cloud API access token."
  type        = string
  sensitive   = true
}

variable "whatsapp_phone_number_id" {
  description = "Meta WhatsApp phone number ID."
  type        = string
  default     = ""
}

variable "whatsapp_verify_token" {
  description = "Random token used by Meta during webhook verification."
  type        = string
  sensitive   = true
}

variable "whatsapp_app_secret" {
  description = "Meta app secret used to verify X-Hub-Signature-256."
  type        = string
  sensitive   = true
}

variable "openai_api_key" {
  description = "OpenAI API key."
  type        = string
  sensitive   = true
}

variable "openai_model" {
  description = "OpenAI model used by the NLP service."
  type        = string
  default     = "gpt-5.4-nano"
}

variable "rdstation_token" {
  description = "RD Station CRM token."
  type        = string
  sensitive   = true
}

variable "log_level" {
  description = "Application log level."
  type        = string
  default     = "INFO"
}

variable "nlp_context_window" {
  description = "Number of previous messages sent to the NLP service."
  type        = number
  default     = 10
}
