package conversation

import (
	"context"
	"time"

	"synova-rd-workflow/internal/domain"
	"synova-rd-workflow/internal/store/conversation"
)

// Service manages conversation sessions and message history.
type Service struct {
	store         conversation.Store
	contextWindow int
}

// New returns a new conversation Service.
func New(store conversation.Store, contextWindow int) *Service {
	return &Service{store: store, contextWindow: contextWindow}
}

// GetOrCreateSession retrieves or creates a session for the given phone number.
func (s *Service) GetOrCreateSession(ctx context.Context, phoneNumber string) (domain.Session, error) {
	return s.store.GetOrCreateSession(ctx, phoneNumber)
}

// GetRecentHistory returns the last N messages for a session (N = context window).
func (s *Service) GetRecentHistory(ctx context.Context, sessionID string) ([]domain.Message, error) {
	return s.store.GetRecentMessages(ctx, sessionID, s.contextWindow)
}

// SaveUserMessage persists a message sent by the user.
func (s *Service) SaveUserMessage(ctx context.Context, sessionID, content, intent string) error {
	return s.store.SaveMessage(ctx, domain.Message{
		SessionID: sessionID,
		Role:      "user",
		Content:   content,
		Intent:    intent,
		CreatedAt: time.Now(),
	})
}

// SaveAssistantMessage persists a reply generated by the assistant.
func (s *Service) SaveAssistantMessage(ctx context.Context, sessionID, content string) error {
	return s.store.SaveMessage(ctx, domain.Message{
		SessionID: sessionID,
		Role:      "assistant",
		Content:   content,
		CreatedAt: time.Now(),
	})
}
